import Head from "next/head";

export default function About() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>About me</title>
      </Head>
      <h1>about</h1>
    </>
  );
}
