import Head from "next/head";

function Skills() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Keep in touch</title>
      </Head>
    </>
  );
}

export default Skills;
