import EntrySection from "@/modules/entrySection";
import Head from "next/head";

export default function Home() {
  console.log("home");
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>My portfolio</title>
      </Head>
      <EntrySection />
    </>
  );
}
