import Head from "next/head";

function Projects() {
  // console.log(data);
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>My Projects</title>
      </Head>
    </>
  );
}

export default Projects;
