import Header from "@/components/header/header";
import PageLayout from "@/Layout/PageLayout";
import SkillsSection from "@/modules/skillsSection";
import Head from "next/head";

export default function Skills() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>My portfolio</title>
      </Head>
      <SkillsSection />
    </>
  );
}
