import ShowMySkills from "@/components/skills/ShowMySkills";
import Head from "next/head";

function Skills({ data }: any) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>My Skills</title>
      </Head>

      <ShowMySkills data={data} />
    </>
  );
}

export async function getStaticProps({ req }: any) {
  const hostname = req?.headers?.host || "localhost";
  try {
    const API =
      hostname === "localhost"
        ? "http://localhost:8888/cms/wp-json/wp/v2/posts?slug=portfolio"
        : "https://my-cms.vipserv.org/wp-json/wp/v2/posts?slug=portfolio";
    const res = await fetch(API, {
      method: "GET",
    });
    const data = await res.json();
    return {
      props: {
        data: data[0].acf,
      },
    };
  } catch {
    return {
      props: {},
    };
  }
}

export default Skills;
