import ShowMySkills from "@/components/skills/skills";
import Head from "next/head";

function Skills({ data }: any) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>My Skills</title>
      </Head>
      <ShowMySkills data={data} />
    </>
  );
}

export async function getStaticProps() {
  const API = "https://vg2sbmir.directus.app/items/skills";
  const res = await fetch(API, {
    method: "GET",
    headers: {},
  });
  const { data } = await res.json();
  console.log(data);
  return {
    props: {
      data,
    },
  };
}

export default Skills;
